menu:
  Home: /
  Archives: /archives
rss:

#widgets: 
#- tag

#language: zh-CN

archive_date_format: MMM DD
fancybox: true

duoshuo_shortname: badforlabor

google_analytics:
favicon: /favicon.ico
